"""empty message

Revision ID: b0658ea35732
Revises: 8f2e89483503
Create Date: 2020-02-23 18:32:12.132544

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b0658ea35732'
down_revision = '8f2e89483503'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders_meals_association', sa.Column('amount', sa.Integer(), nullable=True))
    op.drop_column('orders_meals_association', 'dttm')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders_meals_association', sa.Column('dttm', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('orders_meals_association', 'amount')
    # ### end Alembic commands ###
